### ISSUE TITLE
`keyword` vs `code` or `reason`

### ISSUE THREAD

**Issue by joshrtay** [bugventure/jsen#19]
The use of `code` and `reason` seems more prevalent in error messages for describing the type of error. Any particular reason for choosing `keyword` over those?

**Comment by bugventure** [comment]
@joshrtay with prior knowledge about how JSON schema works, you can easily identify the cause for the failure when you know which keyword failed. 

I didn't want to use codes because of their cryptic nature, where I'd have to document each code and what it indicates. Keywords in JSON schema already provide the semantics and are well documented.

And I didn't want to use `reason` or a string description, because predefined (hard-coded) strings rarely satisfy all messaging needs in a program, thus most of the time requiring additional customization.
